
spring:
  application:
    name: ApiGateway
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
      - id: users
        uri: lb://AUTHENTIFICATION
        predicates:
          - Path=/api/**
          - Path=/Auth/**
      - id: Produits
        uri: lb://PRODUIT-SERVICE
        predicates:
          - Path=/Produit/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      enable: true

server:
  port: 8090